# We'll use this file for the CI/CD pipeline in milestone 2
name: main pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GEN_AI_STUDIO_API_KEY: ${{ secrets.GEN_AI_STUDIO_API_KEY }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      TEAM18_GITHUB_TOKEN: ${{ secrets.TEAM18_GITHUB_TOKEN }} # GitHub fills this automatically
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r backend/app/requirements.txt

    - name: Run MyPy
      run: mypy backend/app/

    - name: Set Python path
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE/backend" >> $GITHUB_ENV
      
    - name: Run tests
      run: |
        cd backend && python -m pytest tests/ --cov=app --cov-report=term-missing --cov-report=html

## CD
    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build SAM application
      run: |
        sam build --use-container

    - name: Deploy to AWS
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.TEAM18_GITHUB_TOKEN }}
      run: |
        sam deploy \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --stack-name ece461-team-18-phase-2-stack \
          --resolve-s3 \
          --capabilities CAPABILITY_IAM \
          --parameter-overrides \
          "ParameterKey=GITHUBTOKEN,ParameterValue=${GITHUB_TOKEN}" \
          "ParameterKey=HFTOKEN,ParameterValue=${HF_TOKEN}"
